config/routes.rb
Monocle::Application.routes.draw do
  devise_for :accounts, :controllers => { :sessions => "accounts/sessions" }

  resources :events, :only => [:index, :create, :show, :update, :destroy]
  resources :funnels, :only => [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :matrix, :only => [:index] do
    collection do
      get :preload_data
    end
  end
  resources :sessions, :only => [:index, :show]

  match '/account' => 'accounts#show', :as => :account
  match '/monocle' => 'monocle#index', :as => :monocle

  match '/about' => 'home#about', :as => :about
  match '/jobs' => 'home#jobs', :as => :jobs
  match '/press' => 'home#press', :as => :press
  match '/privacy' => 'home#privacy', :as => :privacy
  match '/team' => 'home#team', :as => :team
  match '/terms' => 'home#terms', :as => :terms

  match '/ma' => 'home#ma'

  root :to => "home#index"
end

app/models/funnel.rb
class Funnel
  attr_accessor :_id, :name, :e_ids, :c_at, :u_at

  def self.build(params)
    funnel = Funnel.new

    funnel._id = params["_id"] if params["_id"].present?
    funnel.name = params["name"] if params["name"].present?

    e_ids = []
    if params["e_ids"].present?
      params["e_ids"].each do |e_id|
        e_id = BSON::ObjectId.from_string(e_id) if e_id.is_a?(String)
        e_ids.push(e_id)
      end
    end
    funnel.e_ids = e_ids

    funnel.c_at = params["c_at"] if params["c_at"].present?
    funnel.u_at = params["u_at"] if params["u_at"].present?
    funnel
  end

  def update(params={})
    self.name = params["name"] if params["name"].present?

    if params["e_ids"].present?
      e_ids = []
      params["e_ids"].each do |e_id|
        e_id = BSON::ObjectId.from_string(e_id) if e_id.is_a?(String)
        e_ids.push(e_id)
      end
      self.e_ids = e_ids
    end
  end

  def save(account_id)
    now = Time.now

    if self._id.nil?
      self._id = BSON::ObjectId.new
      @@db.collection("funnels_#{account_id}").insert({_id: _id, name: name, e_ids: e_ids, c_at: now, u_at: now})
    else
      @@db.collection("funnels_#{account_id}").update({_id: _id}, {"$set" => {name: name, e_ids: e_ids, u_at: now}})
    end
  end

  def destroy(account_id)
    @@db.collection("funnels_#{account_id}").remove({_id: self._id})
  end

  def self.all(account_id)
    funnels = []

    funnels_params = @@db.collection("funnels_#{account_id}").find()
    funnels_params.each do |params|
      funnel = generate(params)
      funnels.push(funnel)
    end

    funnels
  end

  def events(account_id)
    events = []
    if e_ids.present?
      e_ids.each do |e_id|
        event = Event.find(account_id, e_id)
        events.push(event)
      end
    end

    events
  end

  @funnels = {}

  def self.find(account_id, id)
    begin
      id = BSON::ObjectId.from_string(id) if id.is_a?(String)
    rescue
      id = nil
    end

    if id.present?
      @funnels[id] ||= generate(@@db.collection("funnels_#{account_id}").find({_id: id}).first)
    end
  end

  private

  def self.generate(params)
    Funnel.build(params)
  end
end

app/controllers/funnels_controller.rb
class FunnelsController < ApplicationController
  before_filter :authenticate_account!

  def index
    @funnels = Funnel.all(current_account.id)
  end

  def new
    @events = Event.all(current_account.id)
  end

  def create
    funnel = Funnel.build(params[:funnel])
    funnel.save(current_account.id)

    redirect_to funnel_path(funnel._id)
  end

  def show
    @funnel = Funnel.find(current_account.id, params[:id])
  end

  def edit
    @funnel = Funnel.find(current_account.id, params[:id])
    @events = Event.all(current_account.id)
  end

  def update
    funnel = Funnel.find(current_account.id, params[:id])
    funnel.update(params[:funnel])
    funnel.save(current_account.id)

    redirect_to funnel_path(funnel._id)
  end

  def destroy
    @funnel = Funnel.find(current_account.id, params[:id])
    @funnel.destroy(current_account.id)

    redirect_to funnels_path
  end
end

app/views/funnels/edit.html.erb
<div class="main">
  <h1>Edit Funnel</h1>

  <%= form_tag(funnel_path(@funnel._id.to_s), :method => "put") do %>
      Name<%= text_field_tag("funnel[name]", @funnel.name) %>
      <br/>
      <% @events.each do |event| %>
        <%= event.display %><%= check_box_tag "funnel[e_ids][]", event._id.to_s, @funnel.e_ids.include?(event._id), {} %><br />
      <% end %>
      <%= submit_tag("Update") %>
  <% end %>
  <br />
  <br />
  <%= link_to "(destroy)", funnel_path(@funnel._id.to_s), :method => :delete, :confirm => "Really destroy?" %>
</div>

app/views/funnels/index.html.erb
<div class="main">
  <h1>Funnels</h1>

  <div>
    Total funnels: <%= @funnels.count %>
    <br/>
    <br/>
    <% @funnels.each do |funnel| %>
        <%= link_to funnel.name, funnel_path(funnel._id.to_s) %><br />
    <% end %>
    <br />
    <br />
    <%=  link_to "New Funnel", new_funnel_path %>
  </div>
</div>

app/views/funnels/new.html.erb
<div class="main">
  <h1>New Funnel</h1>

  <%= form_tag(funnels_path, :method => "post") do %>
      Name<%= text_field_tag("funnel[name]") %>
      <br/>
      <% @events.each do |event| %>
        <%= event.display %><%= check_box_tag "funnel[e_ids][]", event._id.to_s, false, {} %><br />
      <% end %>
      <%= submit_tag("Define") %>
  <% end %>
</div>

app/views/funnels/show.html.erb
<style>
    .chart {
        display: inline-block;
        color: #333;
        height: 300px;
        width: 300px;
        margin: 0 auto;
    }
</style>

<script>
    function drawTargetChart(id, size, values) {
        var strokeWidth = 2;
        var radius = (size - strokeWidth) / 2.0;
        var r = Raphael(id, size, size);

        function getR(area) {
            return Math.sqrt(area / 3.14);
        }

        var area = radius * radius * 3.14;

        var max = 0;
        for (var i = 0; i < values.length; i++) {
            if (values[i] > max) {
                max = values[i];
            }
        }

        var scale = area / max;
        var attrs = function (start) {
            sColor = Raphael.hsb(start, 0.75, 1);
            eColor = Raphael.hsb(start, 1, 1);
            return {"stroke-width":strokeWidth, fill:"90-" + eColor + "-" + sColor};
        }

        var color = 0;
        for (var i = 0; i < values.length; i++) {
            r.circle(size / 2, size / 2, getR(scale * values[i])).attr(attrs(color));
            color += 0.1;
        }
    }

    events = new Array;
</script>

<div class="main">
  <h1>Funnel :: <%= @funnel.name %></h1>

  <div>
    Id: <%= @funnel._id %>
    <br/>
    Created At: <%= @funnel.c_at %>
    <br/>
    Updated At: <%= @funnel.u_at %>
    <br/>
    Events:
    <ul>
      <% @funnel.events(current_account.id).each do |event| %>
          <li>
            <%
               period_30 = Analytic.since(current_account.id, 30.days.ago, event._id).count
               period_7 = Analytic.since(current_account.id, 7.days.ago, event._id).count
               period_1 = Analytic.since(current_account.id, 1.days.ago, event._id).count
            %>
            <%= event.display %> - <%= period_30 %>, <%= period_7 %>, <%= period_1 %>
            <script>
                var values = [<%= period_30 %>, <%= period_7 %>, <%= period_1 %>];
                events.push(values);
            </script>
          </li>
      <% end %>
    </ul>

    <script src="/javascripts/raphael.js" type="text/javascript" charset="utf-8"></script>

    <div id="chart1" class="chart"></div>
    <div id="chart2" class="chart"></div>
    <div id="chart3" class="chart"></div>

    <br/>
    <br/>
    <%= link_to "Edit", edit_funnel_path(@funnel._id.to_s) %>
  </div>
</div>

<script>
    function eventSort(a, b) {
        return b[0] - a[0];
    }

    var eventsSorted = events.sort(eventSort);

    for (var i = 0; i < 3; i++) {
        var values = new Array;
        for (var j = 0; j < events.length; j++) {
            values.push(events[j][i]);
        }

        drawTargetChart("chart" + (i+1), 202, values);
    }
</script>